import random
from win10toast import ToastNotifier

verses = [ # If you want, you can include more verses here.
    "I can do all this through him who gives me strength. – Philippians 4:13",
    "For I know the plans I have for you, declares the Lord. – Jeremiah 29:11",
    "The Lord is my shepherd; I shall not want. – Psalm 23:1",
    "Be strong and courageous. Do not be afraid; do not be discouraged. – Joshua 1:9",
    "But the fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness. – Galatians 5:22",
    "And we know that in all things God works for the good of those who love him. – Romans 8:28",
    "The Lord is my light and my salvation—whom shall I fear? – Psalm 27:1",
    "I will instruct you and teach you in the way you should go. – Psalm 32:8",
    "God is our refuge and strength, an ever-present help in trouble. – Psalm 46:1",
    "Cast all your anxiety on him because he cares for you. – 1 Peter 5:7",
    "My grace is sufficient for you, for my power is made perfect in weakness. – 2 Corinthians 12:9",
    "The steadfast love of the Lord never ceases; his mercies never come to an end. – Lamentations 3:22",
    "The Lord will fight for you; you need only to be still. – Exodus 14:14",
    "Trust in the Lord with all your heart and lean not on your own understanding. – Proverbs 3:5",
    "He gives strength to the weary and increases the power of the weak. – Isaiah 40:29",
    "The name of the Lord is a fortified tower; the righteous run to it and are safe. – Proverbs 18:10",
    "With God all things are possible. – Matthew 19:26",
    "Do not worry about tomorrow, for tomorrow will worry about itself. – Matthew 6:34",
    "The Lord is near to all who call on him. – Psalm 145:18",
    "The peace of God, which transcends all understanding, will guard your hearts and your minds. – Philippians 4:7",
    "You will seek me and find me when you seek me with all your heart. – Jeremiah 29:13",
    "Come to me, all you who are weary and burdened, and I will give you rest. – Matthew 11:28",
    "Be joyful in hope, patient in affliction, faithful in prayer. – Romans 12:12",
    "Fear not, for I am with you; be not dismayed, for I am your God. – Isaiah 41:10",
    "The Lord is gracious and compassionate, slow to anger and rich in love. – Psalm 145:8",
    "Be still, and know that I am God. – Psalm 46:10",
    "The Lord is my rock, my fortress and my deliverer. – Psalm 18:2",
    "I am the way and the truth and the life. – John 14:6",
    "For God so loved the world that he gave his one and only Son. – John 3:16",
    "The righteous person may have many troubles, but the Lord delivers him from them all. – Psalm 34:19",
    "Blessed are the pure in heart, for they will see God. – Matthew 5:8",
    "I have loved you with an everlasting love. – Jeremiah 31:3",
    "Even though I walk through the darkest valley, I will fear no evil. – Psalm 23:4",
    "He heals the brokenhearted and binds up their wounds. – Psalm 147:3",
    "No weapon forged against you will prevail. – Isaiah 54:17",
    "Let us not become weary in doing good. – Galatians 6:9",
    "For where your treasure is, there your heart will be also. – Matthew 6:21",
    "Do everything in love. – 1 Corinthians 16:14",
    "The Lord is faithful, and he will strengthen you and protect you. – 2 Thessalonians 3:3",
    "When I am afraid, I put my trust in you. – Psalm 56:3",
    "Let all that you do be done in love. – 1 Corinthians 16:14",
    "For we walk by faith, not by sight. – 2 Corinthians 5:7",
    "The joy of the Lord is your strength. – Nehemiah 8:10",
    "God did not give us a spirit of fear, but of power, love, and self-discipline. – 2 Timothy 1:7",
    "Love is patient, love is kind. – 1 Corinthians 13:4",
    "I am with you always, to the very end of the age. – Matthew 28:20",
    "You are the light of the world. – Matthew 5:14",
    "Seek first his kingdom and his righteousness, and all these things will be given to you. – Matthew 6:33",
    "The Lord your God is with you, the Mighty Warrior who saves. – Zephaniah 3:17",
    "The Lord is close to the brokenhearted. – Psalm 34:18",
    "We love because he first loved us. – 1 John 4:19",
    "In the beginning, God created the heavens and the earth. – Genesis 1:1",
    "Let the peace of Christ rule in your hearts. – Colossians 3:15",
    "Do not fear, for I have redeemed you; I have summoned you by name. – Isaiah 43:1",
    "A friend loves at all times. – Proverbs 17:17",
    "Every good and perfect gift is from above. – James 1:17",
    "The light shines in the darkness, and the darkness has not overcome it. – John 1:5",
    "Delight yourself in the Lord, and he will give you the desires of your heart. – Psalm 37:4",
    "Let us run with perseverance the race marked out for us. – Hebrews 12:1",
    "God is love. – 1 John 4:8",
    "I will not leave you as orphans; I will come to you. – John 14:18",
    "The grass withers and the flowers fall, but the word of our God endures forever. – Isaiah 40:8",
    "Draw near to God and he will draw near to you. – James 4:8",
    "Rejoice always. – 1 Thessalonians 5:16",
    "Give thanks to the Lord, for he is good. – Psalm 107:1",
    "Be kind and compassionate to one another, forgiving each other. – Ephesians 4:32",
    "Be strong, and let your heart take courage. – Psalm 31:24",
    "Do not be overcome by evil, but overcome evil with good. – Romans 12:21",
    "For the Lord is good; his love endures forever. – Psalm 100:5",
    "Do to others as you would have them do to you. – Luke 6:31",
    "Faith is confidence in what we hope for and assurance about what we do not see. – Hebrews 11:1",
    "A cheerful heart is good medicine. – Proverbs 17:22",
    "If anyone is in Christ, the new creation has come. – 2 Corinthians 5:17",
    "The fear of the Lord is the beginning of wisdom. – Proverbs 9:10",
    "Your word is a lamp for my feet, a light on my path. – Psalm 119:105",
    "The Lord has done great things for us, and we are filled with joy. – Psalm 126:3",
    "Jesus Christ is the same yesterday and today and forever. – Hebrews 13:8",
    "Wait for the Lord; be strong and take heart. – Psalm 27:14",
    "The Lord is my strength and my song. – Exodus 15:2",
    "Rejoice in the Lord always. – Philippians 4:4",
    "As iron sharpens iron, so one person sharpens another. – Proverbs 27:17",
    "Create in me a clean heart, O God. – Psalm 51:10",
    "Blessed are those who trust in the Lord. – Jeremiah 17:7",
    "Therefore, if anyone is in Christ, he is a new creation. – 2 Corinthians 5:17",
    "Count it all joy, my brothers, when you meet trials of various kinds. – James 1:2",
    "The Lord is my helper; I will not be afraid. – Hebrews 13:6",
    "Trust in the Lord and do good. – Psalm 37:3",
    "The Lord will be your everlasting light. – Isaiah 60:19",
    "With God, nothing will be impossible. – Luke 1:37",
    "The righteous will flourish like a palm tree. – Psalm 92:12",
    "God is our refuge and strength, an ever-present help in trouble. – Psalm 46:1",
    "You are precious in my sight, and honored, and I love you. – Isaiah 43:4",
    "Hope in the Lord; for with the Lord there is steadfast love. – Psalm 130:7",
    "His mercies are new every morning. – Lamentations 3:22-23",
    "The Lord makes firm the steps of the one who delights in him. – Psalm 37:23",
    "Take heart; I have overcome the world. – John 16:33",
    "You are my refuge and my fortress. – Psalm 91:2",
    "His mercies are new every morning. – Lamentations 3:23",
    "The Lord is good to those whose hope is in him. – Lamentations 3:25",
    "Hope in the Lord; for with the Lord there is steadfast love. – Psalm 130:7",
]

random_verse = random.choice(verses)

toaster = ToastNotifier()

toaster.show_toast(
    title="Bible Verses to Live By 🕊️",
    msg=random_verse,
    icon_path="icon.ico", # https://iconscout.com/free-icon/orthodox-cross-5922945 By Nikita Golubev
    duration=15,
    threaded=True
)
